#!/bin/sh

tmp=tmp
ver=1.1.0

for name in Makefile doit
do
  sed -e "s/[0-9][0-9]*\\.[0-9][0-9]*\\.[0-9][0-9]*/${ver}/g" < ${name} > ${tmp}
  mv ${tmp} ${name}
done
chmod 755 doit

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
